// Generated by gencpp from file test_pkg/Adding_numbersRequest.msg
// DO NOT EDIT!


#ifndef TEST_PKG_MESSAGE_ADDING_NUMBERSREQUEST_H
#define TEST_PKG_MESSAGE_ADDING_NUMBERSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test_pkg
{
template <class ContainerAllocator>
struct Adding_numbersRequest_
{
  typedef Adding_numbersRequest_<ContainerAllocator> Type;

  Adding_numbersRequest_()
    : x(0)
    , y(0)  {
    }
  Adding_numbersRequest_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)  {
  (void)_alloc;
    }



   typedef int64_t _x_type;
  _x_type x;

   typedef int64_t _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::test_pkg::Adding_numbersRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_pkg::Adding_numbersRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Adding_numbersRequest_

typedef ::test_pkg::Adding_numbersRequest_<std::allocator<void> > Adding_numbersRequest;

typedef boost::shared_ptr< ::test_pkg::Adding_numbersRequest > Adding_numbersRequestPtr;
typedef boost::shared_ptr< ::test_pkg::Adding_numbersRequest const> Adding_numbersRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_pkg::Adding_numbersRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_pkg::Adding_numbersRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::test_pkg::Adding_numbersRequest_<ContainerAllocator1> & lhs, const ::test_pkg::Adding_numbersRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::test_pkg::Adding_numbersRequest_<ContainerAllocator1> & lhs, const ::test_pkg::Adding_numbersRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace test_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::test_pkg::Adding_numbersRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_pkg::Adding_numbersRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_pkg::Adding_numbersRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_pkg::Adding_numbersRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_pkg::Adding_numbersRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_pkg::Adding_numbersRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_pkg::Adding_numbersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3b834ede922a0fff22c43585c533b49f";
  }

  static const char* value(const ::test_pkg::Adding_numbersRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3b834ede922a0fffULL;
  static const uint64_t static_value2 = 0x22c43585c533b49fULL;
};

template<class ContainerAllocator>
struct DataType< ::test_pkg::Adding_numbersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_pkg/Adding_numbersRequest";
  }

  static const char* value(const ::test_pkg::Adding_numbersRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_pkg::Adding_numbersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 x\n"
"int64 y\n"
"\n"
;
  }

  static const char* value(const ::test_pkg::Adding_numbersRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_pkg::Adding_numbersRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Adding_numbersRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_pkg::Adding_numbersRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_pkg::Adding_numbersRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int64_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int64_t>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_PKG_MESSAGE_ADDING_NUMBERSREQUEST_H
