// Generated by gencpp from file test_pkg/Adding_numbers.msg
// DO NOT EDIT!


#ifndef TEST_PKG_MESSAGE_ADDING_NUMBERS_H
#define TEST_PKG_MESSAGE_ADDING_NUMBERS_H

#include <ros/service_traits.h>


#include <test_pkg/Adding_numbersRequest.h>
#include <test_pkg/Adding_numbersResponse.h>


namespace test_pkg
{

struct Adding_numbers
{

typedef Adding_numbersRequest Request;
typedef Adding_numbersResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Adding_numbers
} // namespace test_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test_pkg::Adding_numbers > {
  static const char* value()
  {
    return "875493d2ec8f0bdc18c62960322c94b7";
  }

  static const char* value(const ::test_pkg::Adding_numbers&) { return value(); }
};

template<>
struct DataType< ::test_pkg::Adding_numbers > {
  static const char* value()
  {
    return "test_pkg/Adding_numbers";
  }

  static const char* value(const ::test_pkg::Adding_numbers&) { return value(); }
};


// service_traits::MD5Sum< ::test_pkg::Adding_numbersRequest> should match
// service_traits::MD5Sum< ::test_pkg::Adding_numbers >
template<>
struct MD5Sum< ::test_pkg::Adding_numbersRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test_pkg::Adding_numbers >::value();
  }
  static const char* value(const ::test_pkg::Adding_numbersRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test_pkg::Adding_numbersRequest> should match
// service_traits::DataType< ::test_pkg::Adding_numbers >
template<>
struct DataType< ::test_pkg::Adding_numbersRequest>
{
  static const char* value()
  {
    return DataType< ::test_pkg::Adding_numbers >::value();
  }
  static const char* value(const ::test_pkg::Adding_numbersRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test_pkg::Adding_numbersResponse> should match
// service_traits::MD5Sum< ::test_pkg::Adding_numbers >
template<>
struct MD5Sum< ::test_pkg::Adding_numbersResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test_pkg::Adding_numbers >::value();
  }
  static const char* value(const ::test_pkg::Adding_numbersResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test_pkg::Adding_numbersResponse> should match
// service_traits::DataType< ::test_pkg::Adding_numbers >
template<>
struct DataType< ::test_pkg::Adding_numbersResponse>
{
  static const char* value()
  {
    return DataType< ::test_pkg::Adding_numbers >::value();
  }
  static const char* value(const ::test_pkg::Adding_numbersResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_PKG_MESSAGE_ADDING_NUMBERS_H
