// Generated by gencpp from file test_pkg/Count_wordsRequest.msg
// DO NOT EDIT!


#ifndef TEST_PKG_MESSAGE_COUNT_WORDSREQUEST_H
#define TEST_PKG_MESSAGE_COUNT_WORDSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test_pkg
{
template <class ContainerAllocator>
struct Count_wordsRequest_
{
  typedef Count_wordsRequest_<ContainerAllocator> Type;

  Count_wordsRequest_()
    : line()  {
    }
  Count_wordsRequest_(const ContainerAllocator& _alloc)
    : line(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _line_type;
  _line_type line;





  typedef boost::shared_ptr< ::test_pkg::Count_wordsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_pkg::Count_wordsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Count_wordsRequest_

typedef ::test_pkg::Count_wordsRequest_<std::allocator<void> > Count_wordsRequest;

typedef boost::shared_ptr< ::test_pkg::Count_wordsRequest > Count_wordsRequestPtr;
typedef boost::shared_ptr< ::test_pkg::Count_wordsRequest const> Count_wordsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_pkg::Count_wordsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_pkg::Count_wordsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::test_pkg::Count_wordsRequest_<ContainerAllocator1> & lhs, const ::test_pkg::Count_wordsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.line == rhs.line;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::test_pkg::Count_wordsRequest_<ContainerAllocator1> & lhs, const ::test_pkg::Count_wordsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace test_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::test_pkg::Count_wordsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_pkg::Count_wordsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_pkg::Count_wordsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_pkg::Count_wordsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_pkg::Count_wordsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_pkg::Count_wordsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_pkg::Count_wordsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5c74f2920fe696c465ee011cedd4ca6e";
  }

  static const char* value(const ::test_pkg::Count_wordsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5c74f2920fe696c4ULL;
  static const uint64_t static_value2 = 0x65ee011cedd4ca6eULL;
};

template<class ContainerAllocator>
struct DataType< ::test_pkg::Count_wordsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_pkg/Count_wordsRequest";
  }

  static const char* value(const ::test_pkg::Count_wordsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_pkg::Count_wordsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string line\n"
"\n"
;
  }

  static const char* value(const ::test_pkg::Count_wordsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_pkg::Count_wordsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.line);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Count_wordsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_pkg::Count_wordsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_pkg::Count_wordsRequest_<ContainerAllocator>& v)
  {
    s << indent << "line: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.line);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_PKG_MESSAGE_COUNT_WORDSREQUEST_H
