(cl:defpackage test_pkg-srv
  (:use )
  (:export
   "ADDING_NUMBERS"
   "<ADDING_NUMBERS-REQUEST>"
   "ADDING_NUMBERS-REQUEST"
   "<ADDING_NUMBERS-RESPONSE>"
   "ADDING_NUMBERS-RESPONSE"
   "COUNT_WORDS"
   "<COUNT_WORDS-REQUEST>"
   "COUNT_WORDS-REQUEST"
   "<COUNT_WORDS-RESPONSE>"
   "COUNT_WORDS-RESPONSE"
  ))

